services:

  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile
    environment:
      REALM: ${REALM}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
    ports:
      # - "53:53/tcp" # DNS
      # - "53:53/udp" # DNS
      - "88:88/tcp" # Kerberos
      - "88:88/udp" # Kerberos
      - "135:135/tcp" # RPC
      - "137:137/udp" # NetBIOS Name Service
      - "138:138/udp" # NetBIOS Datagram Service
      - "139:139/tcp" # NetBIOS Session Service
      - "389:389/tcp" # LDAP
      - "389:389/udp" # LDAP
      - "445:445/tcp" # SMB
      - "464:464/tcp" # Kerberos - password change
      - "464:464/udp" # Kerberos - password change
      - "636:636/tcp" # LDAP SSL
      - "3268:3268/tcp" # LDAP Global Catalog
      - "3269:3269/tcp" # LDAP Global Catalog SSL
      - "49152-65535:49152-65535/tcp" # RPC for services such as AD replication and SYSVOL replication
    # restart: always
    networks:
      - sede3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always
    networks:
      - sede3

  # db:
  #   image: mariadb:10.6.4-focal
  #   mem_limit: 2g
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
  #   restart: always  
  #   networks:
  #     - sede3

  # wordpress:
  #   image: wordpress:latest
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  #   depends_on:
  #     - db
  #   restart: always
    # networks:
    #   - sede3

  # openvpn-as:
  #   image: openvpn/openvpn-as
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - "943:943"
  #     - "443:443"
  #     - "1194:1194/udp"
  #   volumes:
  #     - ./vpn:/openvpn
  #   restart: always
  #   networks:
  #     - sede3

networks:
    sede3:
      driver: bridge
